### ISSUE TITLE
cant unpack .psx

### ISSUE THREAD

**Issue by 1upus** [krystalgamer/spidey-tools#1]
Hi, trying to unpack some .psx files from n-gage THPS game, but...
Can you chek files?
https://github.com/1upus/N-Gage_stuff/blob/master/temp/nng_thps_psx.7z
thx

**Comment by krystalgamer** [comment]
Sorry, I can't. Due to lack of time I've been unable to to keep working on this project.
That said I can't say why this is not working for other games rather Spiderman 2000(PC).
